---
# ====== Application: test_login =============================
id: 128
identification: 
  name: test_login
  alias: TEST-LOGIN
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 22791866076812490

authorization: 
  authorization-scheme: Reader Rights # 22798198091812557
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: MOVIESTREAM

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: test_login

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 22792674943812496

navigation-bar: 
  implementation: List
  list: Navigation Bar # 22793806898812520
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 45591961210834

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: test_login

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 22787361382812479
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 45591960708210

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 22787662089812482
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 45591960708632

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 22787995918812483
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 45591960708680

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 22788253696812483
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 45591960708741

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 22788596675812484
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 45591960708784

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 22788856753812484
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 45591960708845

- # ====== Component Setting: NATIVE_IR ========================
  id: 22789124215812485
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 45591960708928

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 22789439758812485
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 45591960709015

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 22789716937812486
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 45591960709101

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 22790070863812486
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 45591960709156

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 22790323965812487
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 45591960709191

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 22790622794812487
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 45591960709242

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 22790905863812488
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 45591960709283

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 22791233116812488
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 45591960709316

application-settings: 
- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 22798910947812562
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ACL_ONLY
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  subscription: 
    version-number: 45591960718037

  configuration: 
    build-option: 'Feature: Access Control' # 22796375182812546

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

