create or replace force editionable view master_view (
    directory_id,
    directory,
    facility_disp,
    facility_desc,
    facility_id,
    rco_directory_id,
    encounter_org,
    aff_fac_pool_alias,
    cluster_,
    bldg_disp,
    bldg_desc,
    building_id,
    facility_disp_id,
    nurse_unit_disp,
    nurse_unit_desc,
    nu_outbound_alias,
    nurse_id,
    bldg_disp_id,
    patient_type,
    patient_type_alias,
    medical_service,
    op_prefix,
    aff_srvc_pool_alias,
    med_svc_alias,
    patient_service_code,
    patient_service_description,
    status,
    added_dt,
    inactive_dt
) as
    select
        rd.id as directory_id,
        directory,
        facility_disp,
        facility_desc,
        fd.id as facility_id,
        rco_directory_id,
        encounter_org,
        aff_fac_pool_alias,
        cluster_,
        bldg_disp,
        bldg_desc,
        bd.id as building_id,
        facility_disp_id,
        nurse_unit_disp,
        nurse_unit_desc,
        nu_outbound_alias,
        nd.id as nurse_id,
        bldg_disp_id,
        patient_type,
        patient_type_alias,
        medical_service,
        op_prefix,
        aff_srvc_pool_alias,
        med_svc_alias,
        patient_service_code,
        patient_service_description,
        status,
        added_dt,
        inactive_dt
    from
        rco_directory   rd,
        facility_disp   fd,
        bldg_disp       bd,
        nurse_unit_disp nd;


-- sqlcl_snapshot {"hash":"40952c44bf448333295fc083a8b6f8df9c431c9c","type":"VIEW","name":"MASTER_VIEW","schemaName":"MOVIESTREAM","sxml":""}