---
# ====== Application: Sample REST Services ===================
id: 119
identification: 
  name: Sample REST Services
  alias: SAMPLE-REST-SERVICES
  version: 24.2.0
  application-group: Sample Apps # 8966220573157898

row-search: 
  tokenize: false
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: false
  logging: true
  debugging: true
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: N
  copyright-banner: |
    Name: #APP_NAME#
    Copyright (c) 2012, #YEAR# Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0
    as shown at https://oss.oracle.com/licenses/upl/

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: APEX Auth # 10563475101487172413

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Enabled for Public Sessions

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Disabled
  embed-in-frames: Allow from same origin
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: MOVIESTREAM

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: No NLS (Application not translated)
  automatic-time-zone: false
  automatic-csv-encoding: false

application-format-masks: 
  date: YYYY/MM/DD

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: '&APP_NAME.'

progressive-web-app: 
  enable: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&SESSION.'
    page: 1 # Example REST Application

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&SESSION.'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 3631449168514746257

navigation-bar: 
  implementation: List
  list: Navigation Bar (Top) # 3631488451563793425
  list-template: Navigation Bar

javascript: 
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#IMAGE_PREFIX#pkgapp_ui/css/5.0#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: true
  auto-dismiss-success-messages: false

subscription: 
  version-number: 187810253

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Sample REST Services

component-settings: 
- # ====== Component Setting: NATIVE_BOSS ======================
  id: 40824743814340386
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 187800382

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 42391412069867435
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 37166093930379

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 42421248045834977
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 37167665079388

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 42421629552834978
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 37167665079388

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 42441906863676616
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 155472274

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 140671041778229283
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 37166093930379

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 162269913813101059
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 37166093930381

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 164040373477818846
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 37166093930381

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 216955748729847199
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 37166093930382

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 647653693443129145
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 37166093929872

- # ====== Component Setting: NATIVE_IR ========================
  id: 1875119250234013893
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 37166093930383

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 1960975097268959642
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 37166093930384

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 2977913909167313587
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 37166093930385

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 3624119103628193631
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 37166093930385

