---
# ====== Application: OKTA_SSO ===============================
id: 123
identification: 
  name: OKTA_SSO
  alias: OKTA-SSO
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: OKTA_SSO # 17678489401311414

authorization: 
  source-for-role-or-group-schemes: Custom Code

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: MOVIESTREAM

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: OKTA_SSO

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 17662560631239819

navigation-bar: 
  implementation: List
  list: Navigation Bar # 17663626942239885
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 45041235845817

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: OKTA_SSO

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 17657259501239800
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 45040751553568

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 17657539682239803
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 45040751554133

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 17657848637239804
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 45040751554250

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 17658191954239805
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 45040751554373

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 17658401173239806
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 45040751554554

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 17658709841239806
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 45040751554794

- # ====== Component Setting: NATIVE_IR ========================
  id: 17659069115239807
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 45040751554947

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 17659378955239807
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 45040751555082

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 17659697217239808
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 45040751555339

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 17659907179239808
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 45040751555509

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 17660205479239809
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 45040751555617

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 17660589479239809
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 45040751555732

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 17660871292239810
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 45040751555836

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 17661127708239810
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 45040751555910

