---
# ====== Application: Create GenAI Prompt ====================
id: 100
identification: 
  name: Create GenAI Prompt
  alias: GENAI-PROJECTS
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: false
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 22350029921508549

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: MOVIESTREAM

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Image and Text
  image-url: '#APP_FILES#app-100-logo.png'
  text: Autonomous Database Select AI

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:4:&SESSION.'
    page: 4 # GenAI Projects

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Top Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-tabLike
  list-position: Top
  list: Navigation Menu # 22350868966508555

navigation-bar: 
  implementation: List
  list: Navigation Bar # 22639616971508972
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Create GenAI Prompt

component-settings: 
- # ====== Component Setting: NATIVE_BOSS ======================
  id: 1457892269103564
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 44702215372720

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 7690650685349056
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 44454621705187

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 7691464283349059
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 44454621705191

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 7691522440349059
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 44454621705191

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 22346706471508544
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 41043038235139

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 22347002803508546
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 41043038235281

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 22347296837508547
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 41043038235288

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 22347635421508547
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 41043038235294

- # ====== Component Setting: NATIVE_IR ========================
  id: 22347980079508547
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 41043038235302

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 22348215292508547
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 41043038235306

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 22348558068508547
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 41043038235312

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 22348817704508547
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 41043038235324

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 22349184049508548
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 41043038235337

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 22349486834508548
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 41043038235343

